apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::406512312646:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-13T04:56:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1336"
  uid: eab25682-094d-4e81-a3f8-49d67d880d25
