apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::406512312646:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::406512312646:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CVSOO1UFPRGO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-13T14:26:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1142"
  uid: 226fe0c3-5168-434f-bb10-dbf7d3eb01af
